components:
  answer_builder:
    init_parameters:
      pattern: The answer is "(valid|invalid)".
      reference_pattern: null
    type: haystack.components.builders.answer_builder.AnswerBuilder
  bm25_retriever:
    init_parameters:
      document_store:
        init_parameters:
          bm25_algorithm: BM25L
          bm25_parameters: &id001 {}
          bm25_tokenization_regex: (?u)\b\w\w+\b
          embedding_similarity_function: dot_product
          index: d3e9c471-1c4e-4e3e-9c5a-03aee7147ac1
        type: haystack.document_stores.in_memory.document_store.InMemoryDocumentStore
      filter_policy: replace
      filters: null
      scale_score: false
      top_k: 10
    type: haystack.components.retrievers.in_memory.bm25_retriever.InMemoryBM25Retriever
  embedding_retriever:
    init_parameters:
      document_store:
        init_parameters:
          bm25_algorithm: BM25L
          bm25_parameters: *id001
          bm25_tokenization_regex: (?u)\b\w\w+\b
          embedding_similarity_function: dot_product
          index: d3e9c471-1c4e-4e3e-9c5a-03aee7147ac1
        type: haystack.document_stores.in_memory.document_store.InMemoryDocumentStore
      filter_policy: replace
      filters: null
      return_embedding: false
      scale_score: false
      top_k: 10
    type: haystack.components.retrievers.in_memory.embedding_retriever.InMemoryEmbeddingRetriever
  joiner:
    init_parameters:
      join_mode: merge
      sort_by_score: true
      top_k: 10
      weights: 0.33
    type: haystack.components.joiners.document_joiner.DocumentJoiner
  llm:
    init_parameters:
      api_base_url: null
      api_key:
        env_vars:
        - OPENAI_API_KEY
        strict: true
        type: env_var
      generation_kwargs: {}
      model: gpt-4o-mini
      organization: null
      streaming_callback: null
      system_prompt: null
    type: haystack.components.generators.openai.OpenAIGenerator
  prompt_builder:
    init_parameters:
      required_variables: null
      template: '

        Given these documents, answer the question.

        Your answer is used within a pipeline and must follow the following format:
        "The answer is "valid"" or "The answer is "invalid"" with quotation marks.
        Also allowed are "yes" or "no", "true" or "false", "1" or "0". After stating
        your answer, explain your answer in detail.

        Example: Question: London is the capital of France. Answer: "false", because
        the capital of France is Paris, not London.

        Documents:

        {% for doc in documents %}\

        {{ doc.content }}

        {% endfor %}

        Question: {{query}}

        Answer:

        '
      variables: null
    type: haystack.components.builders.prompt_builder.PromptBuilder
  text_embedder:
    init_parameters:
      api_base_url: null
      api_key:
        env_vars:
        - OPENAI_API_KEY
        strict: true
        type: env_var
      dimensions: null
      model: text-embedding-3-small
      organization: null
      prefix: ''
      suffix: ''
    type: haystack.components.embedders.openai_text_embedder.OpenAITextEmbedder
connections:
- receiver: llm.prompt
  sender: prompt_builder.prompt
- receiver: prompt_builder.documents
  sender: joiner.documents
- receiver: joiner.documents
  sender: bm25_retriever.documents
- receiver: embedding_retriever.query_embedding
  sender: text_embedder.embedding
- receiver: joiner.documents
  sender: embedding_retriever.documents
- receiver: answer_builder.replies
  sender: llm.replies
max_runs_per_component: 100
metadata: {}
