components:
  llm:
    init_parameters:
      api_base_url: null
      api_key:
        env_vars:
        - OPENAI_API_KEY
        strict: true
        type: env_var
      generation_kwargs: {}
      model: gpt-4o-mini
      organization: null
      streaming_callback: null
      system_prompt: null
    type: haystack.components.generators.openai.OpenAIGenerator
  prompt_builder:
    init_parameters:
      required_variables: null
      template: '

        "Given these documents, answer the question: 
        {{ query }}

        Your answer is used within a pipeline and must follow the following format:
        "valid" or "invalid". Make sure to avoid white spaces or other characters.
        
        Answer:"

        '
      variables: null
    type: haystack.components.builders.prompt_builder.PromptBuilder
connections:
- receiver: llm.prompt
  sender: prompt_builder.prompt
max_runs_per_component: 1
metadata: {}
